import * as stylex from "@stylexjs/stylex";
import type { Metadata } from "next";
import { dracula } from "../tokens/theme.stylex";

export const metadata: Metadata = {
  title: "stylex radix",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ja">
      <body {...stylex.props(dracula)}>{children}</body>
    </html>
  );
}
